import firestore from '@react-native-firebase/firestore'

type ParsedTransaction = {
  amount: number
  type: 'debit' | 'credit'
  vendor?: string
  timestamp: number
  message: string
}

// 1. Check if it’s a financial notification
export const isFinancialMessage = (msg: string): boolean => {
  return /(?:debited|credited|txn|spent|Rs\.?\s?\d+)/i.test(msg)
}

// 2. Parse the message to extract transaction info
export const parseMessage = (msg: string): ParsedTransaction | null => {
  try {
    const amountMatch = msg.match(/Rs\.?\s?([\d,]+\.?\d{0,2})/)
    const type = msg.toLowerCase().includes('debited') || msg.toLowerCase().includes('spent')
      ? 'debit'
      : 'credit'

    if (!amountMatch) return null

    const amount = parseFloat(amountMatch[1].replace(/,/g, ''))
    const vendorMatch = msg.match(/at\s([A-Za-z0-9& ]+)/i)
    const vendor = vendorMatch?.[1]?.trim()

    return {
      amount,
      type,
      vendor,
      timestamp: Date.now(),
      message: msg
    }
  } catch (err) {
    console.error('Parsing failed:', err)
    return null
  }
}

// 3. Save to Firestore with autoGenerated + reviewed
export const saveParsedTransaction = async (
  uid: string,
  txn: ParsedTransaction
): Promise<void> => {
  try {
    await firestore()
      .collection('users')
      .doc(uid)
      .collection('transactions')
      .add({
        amount: txn.amount,
        category: 'auto',
        createdAt: txn.timestamp,
        paymentMethod: 'bank',
        note: txn.vendor ? `Auto from ${txn.vendor}` : 'Auto-imported',
        autoGenerated: true,
        reviewed: false,
        originalMessage: txn.message
      })
  } catch (err) {
    console.error('Firestore save failed:', err)
  }
}
