import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    padding: 20,
    paddingBottom: 40,
    backgroundColor: "#1a1a1a",
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 20,
    textAlign: "left",
    color: "#ff4d4d",
  },
  inputGroup: {
    marginBottom: 15,
  },
  label: {
    fontSize: 16,
    marginBottom: 5,
    fontWeight: "500",
    color: "#ff4d4d",
  },
  input: {
    height: 50,
    borderWidth: 1,
    borderColor: "#ff4d4d",
    borderRadius: 8,
    paddingHorizontal: 15,
    fontSize: 16,
    backgroundColor: "#1e1e1e",
    color: "#fff",
  },
  datePickerContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#ff4d4d",
    borderRadius: 8,
    paddingHorizontal: 10,
    height: 50,
    backgroundColor: "#1e1e1e",
  },
  dateButton: {
    padding: 10,
    backgroundColor: "#1e1e1e",
    borderRadius: 8,
  },
  dateText: {
    fontSize: 16,
    color: "#fff",
  },
  buttonContainer: {
    margin: 20,
    borderRadius: 8,
  },
  bubbleContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  bubble: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderWidth: 1,
    borderColor: "#ff4d4d",
    borderRadius: 20,
    backgroundColor: "#1a1a1a",
    marginRight: 10,
    marginBottom: 10,
  },
  bubbleSelected: {
    backgroundColor: "#ff4d4d",
  },
  bubbleText: {
    marginLeft: 5,
    fontSize: 16,
    color: "#ff4d4d",
  },
  bubbleTextSelected: {
    color: "#fff",
  },
  otherCategory: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#ff4d4d",
    backgroundColor: "#262626",
    marginBottom: 10,
  },
  otherInput: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#ff4d4d",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 16,
    backgroundColor: "#1a1a1a",
    color: "#fff",
  },
  paymentMethodContainer: {
    padding: 10,
    backgroundColor: "#1a1a1a",
    borderWidth: 1,
    borderColor: "#ff4d4d",
    borderRadius: 10,
  },
  paymentOption: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderColor: "#ff4d4d",
  },
  paymentOptionText: {
    fontSize: 16,
    color: "#ff4d4d",
  },
  paymentOptionSelected: {
    backgroundColor: "#ff4d4d",
  },
  paymentOptionTextSelected: {
    color: "#fff",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    backgroundColor: "#1a1a1a",
    padding: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ff4d4d",
    width: "80%",
  },
  closeModalButton: {
    marginTop: 10,
    backgroundColor: "#ff4d4d",
    paddingVertical: 10,
    borderRadius: 5,
    alignItems: "center",
  },
  closeModalText: {
    fontSize: 16,
    color: "#fff",
  },
  dropdown: {
    borderWidth: 1,
    borderColor: "#ff4d4d",
    padding: 10,
    borderRadius: 8,
    backgroundColor: "#1a1a1a",
    marginTop: 8,
  },
  dropdownText: {
    fontSize: 16,
    color: "#fff",
  },
  modalOption: {
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#ff4d4d",
  },
  modalOptionText: {
    fontSize: 16,
    color: "#fff",
  },
});

export default styles;
